// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19xndWdqfRXkukcd5QVl4ZgaVe6RNnmM',
    appId: '1:245451810013:web:a72965cff20d6c34b12734',
    messagingSenderId: '245451810013',
    projectId: 'hospitalappointment-6cf61',
    authDomain: 'hospitalappointment-6cf61.firebaseapp.com',
    storageBucket: 'hospitalappointment-6cf61.appspot.com',
    measurementId: 'G-16LX3BSNF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcfEjk0lftfdoliXApN1FGu6kpeTkxPFs',
    appId: '1:245451810013:android:ea3cbf7a8c10c8f8b12734',
    messagingSenderId: '245451810013',
    projectId: 'hospitalappointment-6cf61',
    storageBucket: 'hospitalappointment-6cf61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0CgylSbv-NW6mCIp6mIJQRFiND4jLrB4',
    appId: '1:245451810013:ios:2e48d9cc41ff7c6fb12734',
    messagingSenderId: '245451810013',
    projectId: 'hospitalappointment-6cf61',
    storageBucket: 'hospitalappointment-6cf61.appspot.com',
    iosBundleId: 'com.example.medibookings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0CgylSbv-NW6mCIp6mIJQRFiND4jLrB4',
    appId: '1:245451810013:ios:5e3c3002b1b4c762b12734',
    messagingSenderId: '245451810013',
    projectId: 'hospitalappointment-6cf61',
    storageBucket: 'hospitalappointment-6cf61.appspot.com',
    iosBundleId: 'com.example.medibookings.RunnerTests',
  );
}
